baseURL = 'https://gofenris.com/'
title = 'Fenris'

# Theme ananke
theme = 'ananke'

# options
enableRobotsTXT = true

languageCode = 'en-us'
# defaultContentLanguage = "en"
# sectionPagesMenu = "main"

[pagination]
pagerSize = 5

[taxonomies] 
  category = "categories" 

[params]
  # text_color = ""
  favicon = true
  author = "Aman Ahuja"
  site_logo = "/images/fenris/fenris_logo_2a_t_small2.png"
      # images/fenris_logo_2a_bw.png"
      # images/fenris_logo_2ct_nb.png"
  description = "We are fenris: data initiatives for public benefit."

  background_color_class = "bg-fa-blue"
  custom_css = ["assets/custom.css"] 

  # content display on home
  recent_copy = "Announcements"
  mainSections = ["post"]
  recent_posts_number = 1
  show_reading_time = false

  [[params.ananke_socials]]
  # Social: instagram, facebook, youtube, gitlab, mastodon, slack, stackoverflow, rss
  name = "github"
  url = "https://github.com/gofenris/"

[menus]
  [[menus.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menus.main]]
  name = "About"
  identifier = "About"
  weight = 200
  url = "/#about"


[sitemap] 
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

