baseURL = 'https://gofenris.com/'
languageCode = 'en-us'
title = 'Fenris'

# Theme ananke, modified
theme = 'ananke'

Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[taxonomies] 
  category = "categories" 

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  identifier = "About"
  weight = 200
  url = "/#about"

[params]
  favicon = true
  author = "Aman Ahuja"
  site_logo = "/images/fenris/fenris_logo_2a_t_small2.png"
      # images/fenris_logo_2a_bw.png"
      # images/fenris_logo_2ct_nb.png"
  description = "We are fenris: data initiatives for public benefit."

  # Social: instagram, facebook, youtube, gitlab, mastodon, slack, stackoverflow, rss

  background_color_class = "bg-fa-blue"
  custom_css = ["assets/custom.css"] 

  # content display on home
  recent_copy = "Announcements"
  mainSections = ["post"]
  recent_posts_number = 3
  show_reading_time = false

[sitemap] 
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

